//*---------------------------------------------------------------------------------
//| ODBC Test Tool
//|		Copyright (c) Microsoft, All rights reserved
//|
//| Title:	OPTIONS.C
//|
//| Purpose:
//|		Header file for user options dialog and .INI file access.
//*---------------------------------------------------------------------------------
#ifndef OPTIONS_DEFS
#define OPTIONS_DEFS

//----------------------------------------------------------------------------------
//		Defines and macros
//----------------------------------------------------------------------------------
#define IDD_PICKFONT						  1600

//----------------------------------------------------------------------------------
#define DEX_QUIET_MODE	  10			// Index of SQL_QUIET_MODE in SetConnectOption-fOption default list
#define DEX_QUIET_HWND		1			// Index of <hwnd> in linked list for SQL_QUIET_MODE (SetConnectOption)

#define IDC_STATIC			-1

#define IDD_USER_OPTIONS               600
#define IDX_DRIVER_MENUS               601
#define IDX_AUTO_ERROR_CHECK           602
#define IDX_BUFFER_CHECKING            603
#define IDX_NULL_CHECKING              604
#define IDX_VERSION_NUMBERS				605
#define IDX_BINDCOL_ZERO					606
#define IDE_DFT_BUFF_LEN               609
#define IDE_DFT_PARM_LEN					610
#define IDC_LOG_LEVEL                  611
#define IDB_FONTS								612
#define IDT_FONTNAME							613

//
// Following are for cursor lib.  These values must remain
//	fixed since (val % 10 - 1) is the constant value for
// SQL_ODBC_CURSORS (eg: 2L == IDR_CL_USE_DRIVER)
//
#define IDR_CL_DEFAULT						620
#define IDR_CL_USE_IF_NEEDED				621
#define IDR_CL_USE_ODBC						622
#define IDR_CL_USE_DRIVER					623

#define IDD_ROWSET_OPTIONS					625
#define IDX_SHOW_STATUS						626
#define IDX_SHOW_PCBS						627
#define IDX_COLUMN_NAMES					628
#define IDE_RESERVED_ROWS					629
#define IDE_BIND_ALL_BUFFER				630

#define IDR_ODBCVER_25						MENU25
#define IDR_ODBCVER_30						MENU30
#define IDR_ODBCVER_ALL						MENUALL
#define FIRST_VERSION_NUM					IDR_ODBCVER_25
#define LAST_VERSION_NUM					IDR_ODBCVER_ALL

// Full connect stuff
#define IDD_FULL_CONNECT					1650
#define IDC_DATA_SOURCE						1651
#define IDE_USERID							1652
#define IDE_PASSWORD							1653
#define IDC_NEWHENV							1654

#define IDD_DESC_NAME						1655
#define IDC_DESC_NAME_DESC             1656
#define IDT_DESC_NAME_HANDLE				1657

#define API_SQLALLOCCONNECT						1
#define API_SQLALLOCENV								2
#define API_SQLALLOCSTMT							3
#define API_SQLBINDCOL								4
#define API_SQLCANCEL								5
#define API_SQLCOLATTRIBUTES						6
#define API_SQLCONNECT								7
#define API_SQLDESCRIBECOL							8
#define API_SQLDISCONNECT							9
#define API_SQLERROR									10
#define API_SQLEXECDIRECT							11
#define API_SQLEXECUTE								12
#define API_SQLFETCH									13
#define API_SQLFREECONNECT							14
#define API_SQLFREEENV								15
#define API_SQLFREESTMT								16
#define API_SQLGETCURSORNAME						17
#define API_SQLNUMRESULTCOLS						18
#define API_SQLPREPARE								19
#define API_SQLROWCOUNT								20
#define API_SQLSETCURSORNAME						21
#define API_SQLSETPARAM								22
#define API_SQLTRANSACT								23
#define API_SQLCOLUMNS								24
#define API_SQLDRIVERCONNECT						25
#define API_SQLGETCONNECTOPTION					26
#define API_SQLGETDATA								27
#define API_SQLGETFUNCTIONS						28
#define API_SQLGETINFO								29
#define API_SQLGETSTMTOPTION						30
#define API_SQLGETTYPEINFO							31
#define API_SQLPARAMDATA							32
#define API_SQLPUTDATA								33
#define API_SQLSETCONNECTOPTION					34
#define API_SQLSETSTMTOPTION						35
#define API_SQLSPECIALCOLUMNS						36
#define API_SQLSTATISTICS							37
#define API_SQLTABLES								38
#define API_SQLBROWSECONNECT						39
#define API_SQLCOLUMNPRIVILEGES					40
#define API_SQLDATASOURCES							41
#define API_SQLDESCRIBEPARAM						42
#define API_SQLEXTENDEDFETCH						43
#define API_SQLFOREIGNKEYS							44
#define API_SQLMORERESULTS							45
#define API_SQLNATIVESQL							46
#define API_SQLNUMPARAMS							47
#define API_SQLPARAMOPTIONS						48
#define API_SQLPRIMARYKEYS							49
#define API_SQLPROCEDURECOLUMNS					50
#define API_SQLPROCEDURES							51
#define API_SQLSETPOS								52
#define API_SQLSETSCROLLOPTIONS					53
#define API_SQLTABLEPRIVILEGES					54
#define API_SQLDRIVERS								55
#define API_SQLBINDPARAMETER						56
#define API_SQLALLOCHANDLE							57
#define API_SQLBINDPARAM							58
#define API_SQLCLOSECURSOR							59
#define API_SQLCOLATTRIBUTE						60
#define API_SQLCOPYDESC								61
#define API_SQLENDTRAN								62
#define API_SQLFETCHSCROLL							63
#define API_SQLFREEHANDLE							64
#define API_SQLGETCONNECTATTR						65
#define API_SQLGETDESCFIELD						66
#define API_SQLGETDESCREC							67
#define API_SQLGETDIAGFIELD						68
#define API_SQLGETDIAGREC							69
#define API_SQLGETENVATTR							70
#define API_SQLGETSTMTATTR							71
#define API_SQLSETCONNECTATTR						72
#define API_SQLSETDESCFIELD						73
#define API_SQLSETDESCREC							74
#define API_SQLSETENVATTR							75
#define API_SQLSETSTMTATTR							76
#define API_SQLBULKOPERATIONS						77

// ODBC 3.5 API's
#define API_SQLLOCATOR								78
#define API_SQLGETLENGTH							79
#define API_SQLGETPOSITION							80
#define API_SQLGETSUBSTRING						81
#define API_SQLLOCATEDUPDATE						82

#if ODBCVER >= 0x350
#define NUM_APIS										API_SQLLOCATEDUPDATE
#else
#define NUM_APIS										API_SQLBULKOPERATIONS
#endif

#define API_SQLTABLES25								83
#define API_SQLCOLUMNS25							84
#define API_SQLSTATISTICS25						85
#define API_SQLPRIMARYKEYS25						86
#define API_SQLFOREIGNKEYS25						87
#define API_SQLTABLEPRIVILEGES25					88
#define API_SQLCOLUMNPRIVILEGES25				89
#define API_SQLSPECIALCOLUMNS25					90
#define API_SQLPROCEDURES25						91
#define API_SQLPROCEDURECOLUMNS25				92
#define API_SQLCONFIGDATASOURCE					93
#define API_SQLCONFIGDRIVER						94
#define API_SQLCREATEDATASOURCE					95
#define API_SQLGETINSTALLEDDRIVERS				96
#define API_SQLGETPRIVATEPROFILESTRING			97
#define API_SQLINSTALLDRIVER						98
#define API_SQLINSTALLDRIVERMANAGER				99
#define API_SQLINSTALLTRANSLATOR					100
#define API_SQLINSTALLTRANSLATOREX      		101
#define API_SQLMANAGEDATASOURCES					102
#define API_SQLREMOVEDEFAULTDATASOURCE			103
#define API_SQLREMOVEDSNFROMINI					104
#define API_SQLREMOVEDRIVER						105
#define API_SQLREMOVEDRIVERMANAGER				106
#define API_SQLREMOVETRANSLATOR					107
#define API_SQLVALIDDSN								108
#define API_SQLWRITEDSNTOINI						109
#define API_SQLWRITEPRIVATEPROFILESTRING		110
#define API_SQLGETTRANSLATOR						111
#define API_FILL_PARAM								112
#define API_SQLINSTALLERERROR						113
#define API_SQLINSTALLDRIVEREX					114
#define API_SQLPOSTINSTALLERERROR				115
#define API_SQLREADFILEDSN							116
#define API_SQLWRITEFILEDSN						117
#define API_SQLGETCONFIGMODE						118
#define API_SQLSETCONFIGMODE						119


#define FIRST_API										API_SQLALLOCCONNECT
#define LAST_API										API_SQLPROCEDURECOLUMNS25
#define NUM_ODBC_APIS								API_SQLSETCONFIGMODE+1


#define IDM_SQLALLOCCONNECT						IDM_API_BASE+API_SQLALLOCCONNECT
#define IDM_SQLALLOCENV								IDM_API_BASE+API_SQLALLOCENV
#define IDM_SQLALLOCSTMT							IDM_API_BASE+API_SQLALLOCSTMT
#define IDM_SQLBINDCOL								IDM_API_BASE+API_SQLBINDCOL
#define IDM_SQLCANCEL								IDM_API_BASE+API_SQLCANCEL
#define IDM_SQLCOLATTRIBUTES						IDM_API_BASE+API_SQLCOLATTRIBUTES
#define IDM_SQLCONNECT								IDM_API_BASE+API_SQLCONNECT
#define IDM_SQLDESCRIBECOL							IDM_API_BASE+API_SQLDESCRIBECOL
#define IDM_SQLDISCONNECT							IDM_API_BASE+API_SQLDISCONNECT
#define IDM_SQLERROR			  						IDM_API_BASE+API_SQLERROR
#define IDM_SQLEXECDIRECT		   				IDM_API_BASE+API_SQLEXECDIRECT
#define IDM_SQLEXECUTE		   					IDM_API_BASE+API_SQLEXECUTE
#define IDM_SQLFETCH			   					IDM_API_BASE+API_SQLFETCH
#define IDM_SQLFREECONNECT	   					IDM_API_BASE+API_SQLFREECONNECT
#define IDM_SQLFREEENV		   					IDM_API_BASE+API_SQLFREEENV
#define IDM_SQLFREESTMT								IDM_API_BASE+API_SQLFREESTMT
#define IDM_SQLGETCURSORNAME	   				IDM_API_BASE+API_SQLGETCURSORNAME
#define IDM_SQLNUMRESULTCOLS	   				IDM_API_BASE+API_SQLNUMRESULTCOLS
#define IDM_SQLPREPARE		   					IDM_API_BASE+API_SQLPREPARE
#define IDM_SQLROWCOUNT								IDM_API_BASE+API_SQLROWCOUNT
#define IDM_SQLSETCURSORNAME						IDM_API_BASE+API_SQLSETCURSORNAME
#define IDM_SQLSETPARAM								IDM_API_BASE+API_SQLSETPARAM
#define IDM_SQLTRANSACT								IDM_API_BASE+API_SQLTRANSACT
#define IDM_SQLALLOCHANDLE							IDM_API_BASE+API_SQLALLOCHANDLE
#define IDM_SQLBINDPARAM							IDM_API_BASE+API_SQLBINDPARAM
#define IDM_SQLCLOSECURSOR							IDM_API_BASE+API_SQLCLOSECURSOR
#define IDM_SQLCOLATTRIBUTE						IDM_API_BASE+API_SQLCOLATTRIBUTE
#define IDM_SQLCOPYDESC								IDM_API_BASE+API_SQLCOPYDESC
#define IDM_SQLENDTRAN								IDM_API_BASE+API_SQLENDTRAN
#define IDM_SQLFETCHSCROLL							IDM_API_BASE+API_SQLFETCHSCROLL
#define IDM_SQLFREEHANDLE							IDM_API_BASE+API_SQLFREEHANDLE
#define IDM_SQLGETCONNECTATTR						IDM_API_BASE+API_SQLGETCONNECTATTR
#define IDM_SQLGETDESCFIELD						IDM_API_BASE+API_SQLGETDESCFIELD
#define IDM_SQLGETDESCREC							IDM_API_BASE+API_SQLGETDESCREC
#define IDM_SQLGETDIAGFIELD						IDM_API_BASE+API_SQLGETDIAGFIELD
#define IDM_SQLGETDIAGREC							IDM_API_BASE+API_SQLGETDIAGREC
#define IDM_SQLGETENVATTR							IDM_API_BASE+API_SQLGETENVATTR
#define IDM_SQLGETSTMTATTR							IDM_API_BASE+API_SQLGETSTMTATTR
#define IDM_SQLSETCONNECTATTR						IDM_API_BASE+API_SQLSETCONNECTATTR
#define IDM_SQLCOLUMNS								IDM_API_BASE+API_SQLCOLUMNS
#define IDM_SQLDRIVERCONNECT						IDM_API_BASE+API_SQLDRIVERCONNECT
#define IDM_SQLGETCONNECTOPTION					IDM_API_BASE+API_SQLGETCONNECTOPTION
#define IDM_SQLGETDATA								IDM_API_BASE+API_SQLGETDATA
#define IDM_SQLGETFUNCTIONS						IDM_API_BASE+API_SQLGETFUNCTIONS
#define IDM_SQLGETINFO								IDM_API_BASE+API_SQLGETINFO
#define IDM_SQLGETSTMTOPTION						IDM_API_BASE+API_SQLGETSTMTOPTION
#define IDM_SQLGETTYPEINFO							IDM_API_BASE+API_SQLGETTYPEINFO
#define IDM_SQLPARAMDATA							IDM_API_BASE+API_SQLPARAMDATA
#define IDM_SQLPUTDATA								IDM_API_BASE+API_SQLPUTDATA
#define IDM_SQLSETCONNECTOPTION					IDM_API_BASE+API_SQLSETCONNECTOPTION
#define IDM_SQLSETSTMTOPTION						IDM_API_BASE+API_SQLSETSTMTOPTION
#define IDM_SQLSPECIALCOLUMNS						IDM_API_BASE+API_SQLSPECIALCOLUMNS
#define IDM_SQLSTATISTICS		   				IDM_API_BASE+API_SQLSTATISTICS
#define IDM_SQLTABLES			   				IDM_API_BASE+API_SQLTABLES
#define IDM_SQLBROWSECONNECT	   				IDM_API_BASE+API_SQLBROWSECONNECT
#define IDM_SQLCOLUMNPRIVILEGES					IDM_API_BASE+API_SQLCOLUMNPRIVILEGES
#define IDM_SQLDATASOURCES							IDM_API_BASE+API_SQLDATASOURCES
#define IDM_SQLDESCRIBEPARAM						IDM_API_BASE+API_SQLDESCRIBEPARAM
#define IDM_SQLEXTENDEDFETCH						IDM_API_BASE+API_SQLEXTENDEDFETCH
#define IDM_SQLFOREIGNKEYS							IDM_API_BASE+API_SQLFOREIGNKEYS
#define IDM_SQLMORERESULTS							IDM_API_BASE+API_SQLMORERESULTS
#define IDM_SQLNATIVESQL							IDM_API_BASE+API_SQLNATIVESQL
#define IDM_SQLNUMPARAMS							IDM_API_BASE+API_SQLNUMPARAMS
#define IDM_SQLPARAMOPTIONS						IDM_API_BASE+API_SQLPARAMOPTIONS
#define IDM_SQLPRIMARYKEYS							IDM_API_BASE+API_SQLPRIMARYKEYS
#define IDM_SQLPROCEDURECOLUMNS					IDM_API_BASE+API_SQLPROCEDURECOLUMNS
#define IDM_SQLPROCEDURES							IDM_API_BASE+API_SQLPROCEDURES
#define IDM_SQLSETPOS								IDM_API_BASE+API_SQLSETPOS
#define IDM_SQLSETSCROLLOPTIONS					IDM_API_BASE+API_SQLSETSCROLLOPTIONS
#define IDM_SQLTABLEPRIVILEGES					IDM_API_BASE+API_SQLTABLEPRIVILEGES
#define IDM_SQLDRIVERS								IDM_API_BASE+API_SQLDRIVERS
#define IDM_SQLBINDPARAMETER						IDM_API_BASE+API_SQLBINDPARAMETER
#define IDM_SQLSETDESCFIELD						IDM_API_BASE+API_SQLSETDESCFIELD
#define IDM_SQLSETDESCREC							IDM_API_BASE+API_SQLSETDESCREC
#define IDM_SQLSETENVATTR							IDM_API_BASE+API_SQLSETENVATTR
#define IDM_SQLSETSTMTATTR	   					IDM_API_BASE+API_SQLSETSTMTATTR
#define IDM_SQLLOCATOR								IDM_API_BASE+API_SQLLOCATOR
#define IDM_SQLGETLENGTH							IDM_API_BASE+API_SQLGETLENGTH
#define IDM_SQLGETPOSITION							IDM_API_BASE+API_SQLGETPOSITION
#define IDM_SQLGETSUBSTRING						IDM_API_BASE+API_SQLGETSUBSTRING
#define IDM_SQLLOCATEDUPDATE						IDM_API_BASE+API_SQLLOCATEDUPDATE
#define IDM_SQLTABLES25								IDM_API_BASE+API_SQLTABLES25
#define IDM_SQLCOLUMNS25							IDM_API_BASE+API_SQLCOLUMNS25
#define IDM_SQLSTATISTICS25						IDM_API_BASE+API_SQLSTATISTICS25
#define IDM_SQLPRIMARYKEYS25						IDM_API_BASE+API_SQLPRIMARYKEYS25
#define IDM_SQLFOREIGNKEYS25						IDM_API_BASE+API_SQLFOREIGNKEYS25
#define IDM_SQLTABLEPRIVILEGES25					IDM_API_BASE+API_SQLTABLEPRIVILEGES25
#define IDM_SQLCOLUMNPRIVILEGES25				IDM_API_BASE+API_SQLCOLUMNPRIVILEGES25
#define IDM_SQLSPECIALCOLUMNS25					IDM_API_BASE+API_SQLSPECIALCOLUMNS25
#define IDM_SQLPROCEDURES25						IDM_API_BASE+API_SQLPROCEDURES25
#define IDM_SQLPROCEDURECOLUMNS25				IDM_API_BASE+API_SQLPROCEDURECOLUMNS25
#define IDM_SQLCOLATTRIBUTEW						IDM_API_BASE+API_SQLCOLATTRIBUTEW
#define IDM_SQLCONFIGDATASOURCE        		IDM_API_BASE+API_SQLCONFIGDATASOURCE
#define IDM_SQLCONFIGDRIVER            		IDM_API_BASE+API_SQLCONFIGDRIVER
#define IDM_SQLCREATEDATASOURCE        		IDM_API_BASE+API_SQLCREATEDATASOURCE
#define IDM_SQLGETINSTALLEDDRIVERS     		IDM_API_BASE+API_SQLGETINSTALLEDDRIVERS
#define IDM_SQLGETPRIVATEPROFILESTRING 		IDM_API_BASE+API_SQLGETPRIVATEPROFILESTRING
#define IDM_SQLINSTALLDRIVER           		IDM_API_BASE+API_SQLINSTALLDRIVER
#define IDM_SQLINSTALLDRIVERMANAGER    		IDM_API_BASE+API_SQLINSTALLDRIVERMANAGER
#define IDM_SQLINSTALLTRANSLATOR       		IDM_API_BASE+API_SQLINSTALLTRANSLATOR
#define IDM_SQLINSTALLTRANSLATOREX      		IDM_API_BASE+API_SQLINSTALLTRANSLATOREX
#define IDM_SQLMANAGEDATASOURCES       		IDM_API_BASE+API_SQLMANAGEDATASOURCES
#define IDM_SQLREMOVEDEFAULTDATASOURCE 		IDM_API_BASE+API_SQLREMOVEDEFAULTDATASOURCE
#define IDM_SQLREMOVEDSNFROMINI        		IDM_API_BASE+API_SQLREMOVEDSNFROMINI
#define IDM_SQLREMOVEDRIVER            		IDM_API_BASE+API_SQLREMOVEDRIVER
#define IDM_SQLREMOVEDRIVERMANAGER     		IDM_API_BASE+API_SQLREMOVEDRIVERMANAGER
#define IDM_SQLREMOVETRANSLATOR        		IDM_API_BASE+API_SQLREMOVETRANSLATOR
#define IDM_SQLVALIDDSN					   		IDM_API_BASE+API_SQLVALIDDSN
#define IDM_SQLWRITEDSNTOINI			   		IDM_API_BASE+API_SQLWRITEDSNTOINI
#define IDM_SQLWRITEPRIVATEPROFILESTRING		IDM_API_BASE+API_SQLWRITEPRIVATEPROFILESTRING
#define IDM_SQLGETTRANSLATOR						IDM_API_BASE+API_SQLGETTRANSLATOR
#define IDM_SQLINSTALLERERROR						IDM_API_BASE+API_SQLINSTALLERERROR
#define IDM_SQLINSTALLDRIVEREX					IDM_API_BASE+API_SQLINSTALLDRIVEREX
#define IDM_SQLPOSTINSTALLERERROR				IDM_API_BASE+API_SQLPOSTINSTALLERERROR
#define IDM_SQLREADFILEDSN							IDM_API_BASE+API_SQLREADFILEDSN
#define IDM_SQLWRITEFILEDSN						IDM_API_BASE+API_SQLWRITEFILEDSN
#define IDM_SQLBULKOPERATIONS						IDM_API_BASE+API_SQLBULKOPERATIONS
#define IDM_SQLGETCONFIGMODE						IDM_API_BASE+API_SQLGETCONFIGMODE
#define IDM_SQLSETCONFIGMODE						IDM_API_BASE+API_SQLSETCONFIGMODE


#define END_INSTALLER_IDS							IDM_SQLSETCONFIGMODE
#define START_INSTALLER_IDS						IDM_SQLCONFIGDATASOURCE



#define GetDlgInt(hDlg, id, outval, uDft) 											\
{                                                                          \
	BOOL	fErr;                                                             \
	UINT uTmp;	                                                            \
	uTmp = GetDlgItemInt(hDlg, id, &fErr, FALSE);                      		\
	if(fErr)                                                                \
		outval = (SWORD)uTmp;                                               \
	else                                                                    \
		outval = (SWORD)(uDft);                                             \
}


#endif
