
#define ID_STATIC                       10
#define IDD_SQLALLOCCONNECT             20
#define IDCK_AC_PHDBC                   21
#define IDCK_AC_HENV                    22
#define IDD_SQLALLOCENV                 40
#define IDCK_AE_PHENV                   41
#define IDD_SQLALLOCSTMT                60
#define IDCK_AS_PHSTMT                  61
#define IDCK_AS_HDBC                    62
#define IDD_SQLBINDCOL                  80
#define IDE_BC_ICOL                     81
#define IDCB_BC_FCTYPE                  82
#define IDCK_BC_RGBVALUE                83
#define IDE_BC_CBVALUEMAX               84
#define IDCK_BC_PCBVALUE                85
#define IDCK_BC_HSTMT                   86
#define IDD_SQLCANCEL                   100
#define IDCK_C_HSTMT                    101
#define IDD_SQLCOLATTRIBUTES            120
#define IDE_CA_ICOL                     121
#define IDCB_CA_FDESCTYPE               122
#define IDCK_CA_RGBDESC                 123
#define IDE_CA_CBDESCMAX                124
#define IDCK_CA_PCBDESC                 125
#define IDCK_CA_PFDESC                  126
#define IDCB_CA_DESCRIPTION_TYPE        127
#define IDCK_CA_HSTMT                   128
#define IDD_SQLCONNECT                  140
#define IDCB_C_SZDSN                    141
#define IDCB_C_SZUID                    142
#define IDCB_C_SZAUTHSTR                143
#define IDCB_C_CBDSN                    144
#define IDCB_C_CBUID                    145
#define IDCB_C_CBAUTHSTR                146
#define IDCK_C_HDBC                     147
#define IDD_SQLDESCRIBECOL              160
#define IDE_DC_ICOL                     161
#define IDCK_DC_SZCOLNAME               162
#define IDE_DC_CBCOLNAMEMAX             163
#define IDCK_DC_PCBCOLNAME              164
#define IDCK_DC_PFSQLTYPE               165
#define IDCK_DC_PCBCOLDEF               166
#define IDCK_DC_PIBSCALE                167
#define IDCK_DC_PFNULLABLE              168
#define IDCK_DC_HSTMT                   169
#define IDD_SQLDISCONNECT               180
#define IDCK_D_HDBC                     181
#define IDD_SQLERROR                    200
#define IDCK_E_HDBC                     201
#define IDCK_E_HSTMT                    202
#define IDCK_E_SZSQLSTATE               203
#define IDCK_E_PFNATIVEERROR            204
#define IDCK_E_SZERRORMSG               205
#define IDE_E_CBERRORMSGMAX             206
#define IDCK_E_PCBERRORMSG              207
#define IDCK_E_HENV                     208
#define IDD_SQLEXECDIRECT               220
#define IDCB_ED_SZSQLSTR                221
#define IDCB_ED_CBSQLSTR                222
#define IDCK_ED_HSTMT                   223
#define IDD_SQLEXECUTE                  240
#define IDCK_EX_HSTMT                   241
#define IDD_SQLFETCH                    260
#define IDCK_F_HSTMT                    261
#define IDCK_F_DISPLAY_ROWSET			262
#define IDD_SQLFREECONNECT              280
#define IDCK_FC_HDBC                    281
#define IDD_SQLFREEENV                  310
#define IDCK_FE_HENV                    311
#define IDD_SQLFREESTMT                 320
#define IDCB_FS_FOPTION                 321
#define IDCK_FS_HSTMT                   322
#define IDCK_FS_DISPLAY_ROWSET			323

#define IDD_SQLGETCURSORNAME            340
#define IDCK_GCN_SZCURSOR               341
#define IDE_GCN_CBCURSORMAX             342
#define IDCK_GCN_PCBCURSOR              343
#define IDCK_GCN_HSTMT                  344
#define IDD_SQLNEXTCOLUMN               350
#define IDD_SQLGETNESTEDHANDLE          351
#define IDE_GNH_ICOL                   	352
#define IDCK_GNH_HSTMT                 	353
#define IDCK_GNH_OUTPUTHANDLE           354
#define IDD_SQLSTRUCTUREDTYPES          355
#define IDD_SQLSTRUCTUREDTYPECOLUMNS    356
#define IDD_SQLNUMRESULTCOLS            360
#define IDCK_NRC_PCCOL                  361
#define IDCK_NRC_HSTMT                  362
#define IDD_SQLPREPARE                  380
#define IDCB_P_SZSQLSTR                 381
#define IDCB_P_CBSQLSTR                 382
#define IDCK_P_HSTMT                    383
#define IDD_SQLROWCOUNT                 400
#define IDCK_RC_PCROW                   401
#define IDCK_RC_HSTMT                   402
#define IDD_SQLSETCURSORNAME            420
#define IDCB_SCN_SZCURSOR               421
#define IDCB_SCN_CBCURSOR               422
#define IDCK_SCN_HSTMT                  423
#define IDD_SQLTRANSACT                 460
#define IDCK_T_HDBC                     461
#define IDCB_T_FTYPE                    462
#define IDCK_T_HENV                     463
#define IDD_SQLALLOCHANDLE              480
#define IDCB_AH_FHANDLETYPE             481
#define IDCB_AH_INPUTHANDLE             482
#define IDCK_AH_OUTPUTHANDLE            483
#define IDD_SQLBINDPARAM                500
#define IDCB_BP_HSTMT                   501
#define IDE_BP_IPAR                     502
#define IDCB_BP_FCTYPE                  503
#define IDCB_BP_FSQLTYPE                504
#define IDE_BP_CBCOLDEF                 505
#define IDE_BP_IBSCALE                  506
#define IDCB_BP_RGBVALUE                507
#define IDCB_BP_PCBVALUE                508
#define IDCK_BP_SQL_LEN_DATA_AT_EXEC    509
#define IDCB_BP_ROWSET_HDBC					520
#define IDCB_BP_ROWSET_HDBC_TXT           521
#define IDCB_BP_ROWSET_HSTMT            	540
#define IDCB_BP_ROWSET_HSTMT_TXT          541
#define IDE_BP_COLUMN                   	542
#define IDE_BP_COLUMN_TXT                 543
#define IDE_BP_ROW                      	544
#define IDE_BP_ROW_TXT							545
#define IDE_BP_BUFFER_SIZE              	546
#define IDD_SQLCLOSECURSOR              	547
#define IDCB_CC_HSTMT                   	548
#define IDD_SQLCOLATTRIBUTE             	560
#define IDCB_CA_HSTMT                   	561
#define IDE_CA_ICOLUMNNUMBER            	562
#define IDCB_CA_FFIELDINDENTIFIER       	580
#define IDCK_CA_RGBCHARACTERATTRIBUTE   	581
#define IDE_CA_CBBUFFERLENGTH           	582
#define IDCK_CA_PCBSTRINGLENGTH         	583
#define IDCK_CA_PVNUMERICATTRIBUTE      	610
#define IDCB_CA_FFIELDINDENTIFIER_TYPE  	611
#define IDD_SQLCOPYDESC                 	612
#define IDCB_CD_HSRCDESC                	613
#define IDCB_CD_HDESTDESC               	620
#define IDD_SQLENDTRAN                  	621
#define IDCB_ET_FHANDLETYPE             	622
#define IDCB_ET_HHANDLE                 	640
#define IDCB_ET_FCOMPLETIONTYPE         	641
#define IDD_SQLFETCHSCROLL              	642
#define IDCB_FS_HSTMT                   	643
#define IDCB_FS_FFETCHORIENTATION       	644
#define IDE_FS_FFETCHOFFSET             	645
#define IDD_SQLFREEHANDLE               	646
#define IDCB_FH_FHANDLETYPE             	660
#define IDCB_FH_INPUTHANDLE             	661
#define IDD_SQLGETCONNECTATTR           	662
#define IDCB_GCA_FATTRIBUTE             	663
#define IDCK_GCA_RGBVALUE               	664
#define IDE_GCA_CBVALUE                 	665
#define IDCK_GCA_PCBVALUE               	666
#define IDCB_GCA_PARAMETER_TYPE         	680
#define IDCB_GCA_HDBC                   	681
#define IDD_SQLGETDESCFIELD             	682
#define IDCB_GDF_HDESC                  	683
#define IDE_GDF_IRECNUM                 	684
#define IDCB_GDF_IFIELDIDENTIFIER       	685
#define IDCK_GDF_RGBVALUE               	686
#define IDE_GDF_CBVALUEMAX              	687
#define IDCK_GDF_PCBVALUE               	688
#define IDCB_GDF_IFIELDIDENTIFIER_TYPE		689
#define IDD_SQLGETDESCREC               	690
#define IDCB_GDR_HDESC                  	691
#define IDE_GDR_IRECNUM                 	700
#define IDCK_GDR_SZNAME                 	701
#define IDE_GDR_CBNAME                  	702
#define IDCK_GDR_PCBNAME                	703
#define IDCK_GDR_FTYPE                  	704
#define IDCK_GDR_FSUBTYPE               	705
#define IDCK_GDR_PCOLDEF                	706
#define IDCK_GDR_PPRECISION             	707
#define IDCK_GDR_PSCALE                 	708
#define IDCK_GDR_PFNULLABLE             	720
#define IDD_SQLGETDIAGFIELD             	721
#define IDCB_GDF_FHANDLETYPE            	722
#define IDCB_GDF_HHANDLE                	723
#define IDE_GDF_IRECRECNUMBER           	724
#define IDCB_GDF_FDIAGIDENTIFIER        	725
#define IDCK_GDF_RGBDIAGINFO            	726
#define IDE_GDF_CBBUFFERLENGTH          	727
#define IDCK_GDF_PCBSTRINGLENGTH        	728
#define IDCB_GDF_FDIAGIDENTIFIER_TYPE   	740
#define IDD_SQLGETDIAGREC               	741
#define IDCB_GDR_FHANDLETYPE            	742
#define IDCB_GDR_HHANDLE                	743
#define IDE_GDR_IRECRECNUMBER           	744
#define IDCK_GDR_SZSQLSTATE             	745
#define IDCK_GDR_PFNATIVEERROR          	760
#define IDCK_GDR_SZMESSAGETEXT          	761
#define IDE_GDR_CBBUFFERLENGTH          	762
#define IDCK_GDR_PCBTEXTLENGTH          	763
#define IDD_SQLGETENVATTR               	764
#define IDCB_GEA_HENV                   	765
#define IDCB_GEA_FATTRIBUTE             	766
#define IDCK_GEA_RGBVALUE               	780
#define IDE_GEA_CBVALUE                 	781
#define IDCK_GEA_PCBVALUE               	782
#define IDCB_GEA_FATTRIBUTE_TYPE				783
#define IDD_SQLGETSTMTATTR              	784
#define IDCB_GSA_FATTRIBUTE             	785
#define IDCK_GSA_RGBVALUE               	800
#define IDE_GSA_CBVALUE                 	801
#define IDCK_GSA_PCBVALUE               	802
#define IDCB_GSA_PARAMETER_TYPE         	803
#define IDCB_GSA_HSTMT                  	804
#define IDD_SQLSETCONNECTATTR           	805
#define IDCB_SCA_FATTRIBUTE             	806
#define IDCB_SCA_RGBVALUE               	807
#define IDCB_SCA_CBVALUE                	808
#define IDCB_SCA_PARAMETER_TYPE         	809
#define IDCB_SCA_HDBC                   	820
#define IDD_SQLCOLUMNS                  	821
#define IDCB_COL_SZCATALOGNAME          	822
#define IDCB_COL_SZSCHEMANAME           	823
#define IDCB_COL_SZTABLENAME            	824
#define IDCB_COL_SZCOLUMNNAME           	825
#define IDCB_COL_CBCATALOGNAME          	826
#define IDCB_COL_CBSCHEMANAME           	827
#define IDCB_COL_CBTABLENAME            	828
#define IDCB_COL_CBCOLUMNNAME           	840
#define IDCK_COL_HSTMT                  	841
#define IDD_SQLDRIVERCONNECT            	842
#define IDCK_DC_HWND                    	843
#define IDCB_DC_SZCONNSTRIN             	844
#define IDCB_DC_CBCONNSTRIN             	860
#define IDCK_DC_SZCONNSTROUT            	861
#define IDE_DC_CBCONNSTROUTMAX          	862
#define IDCK_DC_PCBCONNSTROUT           	863
#define IDCB_DC_FDRIVERCOMPLETION       	864
#define IDCK_DC_HDBC                    	865
#define IDD_SQLGETCONNECTOPTION         	866
#define IDCB_GCO_FOPTION                	880
#define IDCK_GCO_PVPARAM                	881
#define IDCB_GCO_PARAMETER_TYPE         	882
#define IDCK_GCO_HDBC                   	883
#define IDD_SQLGETDATA                  	900
#define IDE_GD_ICOL                     	901
#define IDCB_GD_FCTYPE                  	902
#define IDCK_GD_RGBVALUE                	903
#define IDE_GD_CBVALUEMAX               	904
#define IDCK_GD_PCBVALUE                	905
#define IDCK_GD_HSTMT                   	906
#define IDD_SQLGETFUNCTIONS             	920
#define IDCB_GF_FFUNCTION               	921
#define IDCK_GF_PFEXISTS                	922
#define IDCK_GF_HDBC                    	923
#define IDD_SQLGETINFO                  	924
#define IDCB_GI_FINFOTYPE               	940
#define IDCK_GI_RGBINFOVALUE            	941
#define IDE_GI_CBINFOVALUEMAX           	942
#define IDCK_GI_PCBINFOVALUE            	960
#define IDCB_GI_INFORMATION_VALUE_TYPE  	961
#define IDCK_GI_HDBC                    	962
#define IDD_SQLGETSTMTOPTION            	980
#define IDCB_GSO_FOPTION                	981
#define IDCK_GSO_PVPARAM                	982
#define IDCB_GSO_PARAMETER_TYPE         	983
#define IDCK_GSO_HSTMT                  	1000
#define IDD_SQLGETTYPEINFO              	1001
#define IDCB_GTI_FSQLTYPE               	1002
#define IDCK_GTI_HSTMT                  	1003
#define IDD_SQLPARAMDATA                	1004
#define IDCK_PD_PRGBVALUE               	1020
#define IDCK_PD_HSTMT                   	1021
#define IDD_SQLPUTDATA                  	1022
#define IDCB_PUT_RGBVALUE               	1023
#define IDCB_PUT_CBVALUE                	1024
#define IDCK_PUT_HSTMT                  	1040
#define IDD_SQLSETCONNECTOPTION         	1041
#define IDCB_SCO_FOPTION                	1042
#define IDCB_SCO_VPARAM                 	1043
#define IDCB_SCO_PARAMETER_TYPE         	1044
#define IDCK_SCO_HDBC                   	1045
#define IDD_SQLSETSTMTOPTION            	1046
#define IDCB_SSO_FOPTION                	1047
#define IDCB_SSO_VPARAM                 	1048
#define IDCB_SSO_PARAMETER_TYPE         	1049
#define IDCK_SSO_HSTMT                  	1050
#define IDD_SQLSPECIALCOLUMNS           	1060
#define IDCB_SC_FCOLTYPE                	1061
#define IDCB_SC_SZCATALOGNAME           	1062
#define IDCB_SC_SZSCHEMANAME            	1063
#define IDCB_SC_SZTABLENAME             	1064
#define IDCB_SC_CBCATALOGNAME           	1065
#define IDCB_SC_CBSCHEMANAME            	1066
#define IDCB_SC_CBTABLENAME             	1067
#define IDCB_SC_FSCOPE                  	1068
#define IDCB_SC_FNULLABLE               	1069
#define IDCK_SC_HSTMT                   	1080
#define IDD_SQLSTATISTICS               	1081
#define IDCB_S_SZCATALOGNAME            	1082
#define IDCB_S_SZSCHEMANAME             	1083
#define IDCB_S_SZTABLENAME              	1084
#define IDCB_S_FUNIQUE                  	1085
#define IDCB_S_CBCATALOGNAME            	1086
#define IDCB_S_CBSCHEMANAME             	1087
#define IDCB_S_CBTABLENAME              	1088
#define IDCB_S_FACCURACY                	1089
#define IDCK_S_HSTMT                    	1100
#define IDD_SQLTABLES                   	1101
#define IDCB_T_SZCATALOGNAME            	1102
#define IDCB_T_SZSCHEMANAME             	1103
#define IDCB_T_SZTABLENAME              	1104
#define IDCB_T_SZTABLETYPE              	1105
#define IDCB_T_CBCATALOGNAME            	1106
#define IDCB_T_CBSCHEMANAME             	1120
#define IDCB_T_CBTABLENAME              	1121
#define IDCB_T_CBTABLETYPE              	1122
#define IDCK_T_HSTMT                    	1123
#define IDD_SQLBROWSECONNECT            	1124
#define IDCB_BC_SZCONNSTRIN             	1125
#define IDCB_BC_CBCONNSTRIN             	1126
#define IDCK_BC_SZCONNSTROUT            	1127
#define IDE_BC_CBCONNSTROUTMAX          	1128
#define IDCK_BC_PCBCONNSTROUT           	1129
#define IDCK_BC_HDBC                    	1140
#define IDD_SQLCOLUMNPRIVILEGES         	1141
#define IDCB_CP_SZCATALOGNAME           	1142
#define IDCB_CP_SZSCHEMANAME            	1143
#define IDCB_CP_SZTABLENAME             	1144
#define IDCB_CP_SZCOLUMNNAME            	1145
#define IDCB_CP_CBCATALOGNAME           	1146
#define IDCB_CP_CBSCHEMANAME            	1147
#define IDCB_CP_CBTABLENAME             	1148
#define IDCB_CP_CBCOLUMNNAME            	1160
#define IDCK_CP_HSTMT                   	1161
#define IDD_SQLDATASOURCES              	1162
#define IDCB_DS_FDIRECTION              	1163
#define IDCK_DS_SZDSN                   	1164
#define IDE_DS_CBDSNMAX                 	1165
#define IDCK_DS_PCBDSN                  	1166
#define IDCK_DS_SZDESCRIPTION           	1180
#define IDE_DS_CBDESCRIPTIONMAX         	1181
#define IDCK_DS_PCBDESCRIPTION          	1182
#define IDCK_DS_HENV                    	1183
#define IDD_SQLDESCRIBEPARAM            	1184
#define IDE_DP_IPAR                     	1185
#define IDCK_DP_PFSQLTYPE               	1200
#define IDCK_DP_PCBCOLDEF               	1201
#define IDCK_DP_PIBSCALE                	1202
#define IDCK_DP_PFNULLABLE              	1203
#define IDCK_DP_HSTMT                   	1204
#define IDD_SQLEXTENDEDFETCH            	1205
#define IDCB_EF_FFETCHTYPE              	1206
#define IDCK_EF_DISPLAY_ROWSET				1207
#define IDE_EF_IROW                     	1208
#define IDCK_EF_PCROW                   	1209
#define IDCK_EF_RGFROWSTATUS            	1210
#define IDCK_EF_HSTMT                   	1211
#define IDD_SQLFOREIGNKEYS              	1212
#define IDCB_FK_SZPKCATALOGNAME         	1213
#define IDCB_FK_SZPKSCHEMANAME          	1214
#define IDCB_FK_SZPKTABLENAME           	1220
#define IDCB_FK_CBPKCATALOGNAME         	1221
#define IDCB_FK_CBPKSCHEMANAME          	1240
#define IDCB_FK_CBPKTABLENAME           	1241
#define IDCB_FK_SZFKCATALOGNAME         	1242
#define IDCB_FK_SZFKSCHEMANAME          	1243
#define IDCB_FK_SZFKTABLENAME           	1244
#define IDCB_FK_CBFKCATALOGNAME         	1245
#define IDCB_FK_CBFKSCHEMANAME          	1246
#define IDCB_FK_CBFKTABLENAME           	1260
#define IDCK_FK_HSTMT                   	1261
#define IDD_SQLMORERESULTS              	1262
#define IDCK_MR_HSTMT                   	1280
#define IDD_SQLNATIVESQL                	1281
#define IDCB_NS_SZSQLSTRIN              	1282
#define IDCB_NS_CBSQLSTRIN              	1283
#define IDCK_NS_SZSQLSTR                	1300
#define IDE_NS_CBSQLSTRMAX              	1301
#define IDCK_NS_PCBSQLSTR               	1302
#define IDCK_NS_HDBC                    	1303
#define IDD_SQLNUMPARAMS                	1304
#define IDCK_NP_PCPAR                   	1305
#define IDCK_NP_HSTMT                   	1306
#define IDD_SQLPARAMOPTIONS             	1307
#define IDE_PO_CROW                     	1320
#define IDCK_PO_PIROW                   	1321
#define IDCK_PO_HSTMT                   	1322
#define IDD_SQLPRIMARYKEYS              	1323
#define IDCB_PK_SZCATALOGNAME           	1324
#define IDCB_PK_SZSCHEMANAME            	1325
#define IDCB_PK_SZTABLENAME             	1326
#define IDCB_PK_CBCATALOGNAME           	1327
#define IDCB_PK_CBSCHEMANAME            	1328
#define IDCB_PK_CBTABLENAME             	1329
#define IDCK_PK_HSTMT                   	1340
#define IDD_SQLPROCEDURECOLUMNS         	1341
#define IDCB_PC_SZPROCCATALOG           	1342
#define IDCB_PC_SZPROCSCHEMA            	1343
#define IDCB_PC_SZPROCNAME              	1344
#define IDCB_PC_SZCOLUMNNAME            	1345
#define IDCB_PC_CBPROCCATALOG           	1346
#define IDCB_PC_CBPROCSCHEMA            	1347
#define IDCB_PC_CBPROCNAME              	1360
#define IDCB_PC_CBCOLUMNNAME            	1361
#define IDCK_PC_HSTMT                   	1362
#define IDD_SQLPROCEDURES               	1363
#define IDCB_PROC_SZPROCCATALOG         	1364
#define IDCB_PROC_SZPROCSCHEMA          	1380
#define IDCB_PROC_SZPROCNAME            	1381
#define IDCB_PROC_CBPROCCATALOG         	1382
#define IDCB_PROC_CBPROCSCHEMA          	1383
#define IDCB_PROC_CBPROCNAME            	1384
#define IDCK_PROC_HSTMT                 	1400
#define IDD_SQLSETPOS                   	1401
#define IDE_SP_IROW                     	1402
#define IDCB_SP_FOPTION                 	1403
#define IDCB_SP_FLOCK                   	1404
#define IDCK_SP_HSTMT                   	1405
#define IDD_SQLSETSCROLLOPTIONS         	1406
#define IDCB_SSOP_FCONCURRENCY          	1407
#define IDCB_SSOP_CROWKEYSET            	1420
#define IDE_SSOP_CROWROWSET             	1421
#define IDCK_SSOP_HSTMT                 	1422
#define IDD_SQLTABLEPRIVILEGES          	1423
#define IDCB_TP_SZCATALOGNAME           	1424
#define IDCB_TP_SZSCHEMANAME            	1425
#define IDCB_TP_SZTABLENAME             	1426
#define IDCB_TP_CBCATALOGNAME           	1427
#define IDCB_TP_CBSCHEMANAME            	1428
#define IDCB_TP_CBTABLENAME             	1440
#define IDCK_TP_HSTMT                   	1441
#define IDD_SQLDRIVERS                  	1442
#define IDCB_D_FDIRECTION               	1443
#define IDCK_D_SZDRIVERDESC             	1444
#define IDE_D_CBDRIVERDESCMAX           	1445
#define IDCK_D_PCBDRIVERDESC            	1446
#define IDCK_D_SZDRIVERATTRIBUTES       	1447
#define IDE_D_CBDRVRATTRMAX             	1448
#define IDCK_D_PCBDRVRATTR              	1449
#define IDCK_D_HENV                     	1450
#define IDD_SQLBINDPARAMETER            	1451
#define IDE_BINDP_IPAR                  	1452
#define IDCB_BINDP_FPARAMTYPE           	1453
#define IDCB_BINDP_FCTYPE               	1454
#define IDCB_BINDP_FSQLTYPE             	1455
#define IDE_BINDP_CBCOLDEF              	1456
#define IDE_BINDP_IBSCALE               	1460
#define IDCB_BINDP_RGBVALUE             	1461
#define IDE_BINDP_CBVALUEMAX            	1462
#define IDCB_BINDP_PCBVALUE             	1463
#define IDCK_BINDP_SQL_LEN_DATA_AT_EXEC 	1464
#define IDCB_BINDP_ROWSET_HDBC          	1465
#define IDGB_BINDP_ROWSET						1466
#define IDCB_BINDP_ROWSET_HDBC_TXT		 	1480
#define IDCB_BINDP_ROWSET_HSTMT         	1481
#define IDCB_BINDP_ROWSET_HSTMT_TXT		 	1482
#define IDE_BINDP_COLUMN                	1483
#define IDE_BINDP_COLUMN_TXT            	1484
#define IDE_BINDP_ROW                   	1485
#define IDE_BINDP_ROW_TXT               	1486
#define IDE_BINDP_BUFFER_SIZE           	1487
#define IDCK_BINDP_HSTMT                	1488
#define IDD_SQLSETDESCFIELD             	1489
#define IDCB_SDF_HDESC                  	1490
#define IDE_SDF_IRECNUM                 	1500
#define IDCB_SDF_IFIELDIDENTIFIER       	1501
#define IDCB_SDF_RGBVALUE               	1502
#define IDE_SDF_CBBUFFERLENGTH          	1503
#define IDCB_SDF_IFIELDIDENTIFIER_TYPE		1504
#define IDD_SQLSETDESCREC               	1520
#define IDCB_SDR_HDESC                  	1521
#define IDE_SDR_IRECNUM                 	1522
#define IDCB_SDR_FTYPE                  	1523
#define IDCB_SDR_FSUBTYPE               	1524
#define IDCB_SDR_FSUBTYPETXT					1525
#define IDE_SDR_CBLENGTH                	1540
#define IDE_SDR_CBCOLDEF                	1541
#define IDE_SDR_IBSCALE                 	1542
#define IDCB_SDR_RGBVALUE               	1543
#define IDCB_SDR_PCBSTRINGLENGTH        	1560
#define IDCK_SDR_PFINDICATOR            	1561
#define IDD_SQLSETENVATTR               	1562
#define IDCB_SEA_HENV                   	1563
#define IDCB_SEA_FATTRIBUTE             	1564
#define IDCB_SEA_RGBVALUE               	1565
#define IDE_SEA_CBVALUE                 	1580
#define IDCB_SEA_FATTRIBUTE_TYPE				1581
#define IDD_SQLSETSTMTATTR              	1582
#define IDCB_SSA_FATTRIBUTE             	1583
#define IDCB_SSA_RGBVALUE               	1584
#define IDE_SSA_CBVALUE                 	1585
#define IDCB_SSA_PARAMETER_TYPE         	1586
#define IDCB_SSA_HSTMT                  	1587
#define IDD_SQLLOCATOR                  	1588
#define IDCB_L_HLOCATOR                 	1589
#define IDCB_L_FOPERATION               	1620
#define IDCK_L_HSTMT                    	1621
#define IDD_SQLGETLENGTH                	1622
#define IDCK_GL_HSTMT                   	1623
#define IDCB_GL_FLOCATORTYPE            	1624
#define IDCB_GL_HLOCATOR                	1625
#define IDCK_GL_PCBVALUE                	1626
#define IDCK_GL_PFINDICATOR             	1627
#define IDD_SQLGETPOSITION              	1628
#define IDCK_GP_HSTMT                   	1629
#define IDCB_GP_FLOCATORTYPE            	1640
#define IDCB_GP_HSOURCELOCATOR          	1641
#define IDCB_GP_HTARGETLOCATOR          	1642
#define IDCB_GP_SZSEARCHSTRING          	1643
#define IDE_GP_CBSEARCHSTRING           	1644
#define IDE_GP_IFROMPOSITION            	1660
#define IDCK_GP_PIBLOCATEDAT            	1661
#define IDCK_GP_PFINDICATOR             	1662
#define IDD_SQLLOCATEDUPDATE            	1663
#define IDCK_LU_HSTMT                   	1664
#define IDCB_LU_FLOCATORTYPE            	1665
#define IDCB_LU_HTARGETLOCATOR          	1666
#define IDE_LU_IFROMPOSITION            	1667
#define IDE_LU_CBFORLENGTH              	1680
#define IDCB_LU_FSOURCETYPE             	1681
#define IDCB_LU_RGBVALUE                	1682
#define IDE_LU_CBVALUE                  	1720
#define IDCK_LU_PFINDICATOR             	1721
#define IDD_SQLCONFIGDATASOURCE         	1722
#define IDCB_CDS_FREQUEST               	1723
#define IDCB_CDS_SZDRIVER               	1740
#define IDCB_CDS_SZATTRIBUTES           	1741
#define IDCK_CDS_HWNDPARENT             	1742
#define IDD_SQLCONFIGDRIVER             	1743
#define IDCK_CD_HWNDPARENT              	1744
#define IDCB_CD_FREQUEST                	1745
#define IDCB_CD_SZDRIVER                	1760
#define IDCB_CD_SZARGS                  	1761
#define IDCK_CD_SZMSG                   	1762
#define IDE_CD_CBMSGMAX                 	1763
#define IDCK_CD_PCBMSGMAX               	1764
#define IDD_SQLCREATEDATASOURCE         	1765
#define IDCB_CRDS_SZDS                  	1780
#define IDCK_CRDS_HWNDPARENT            	1781
#define IDD_SQLGETINSTALLEDDRIVERS      	1782
#define IDCK_GID_SZBUF                  	1783
#define IDE_GID_CBBUFMAX                	1800
#define IDCK_GID_PCBBUFOUT              	1801
#define IDD_SQLGETPRIVATEPROFILESTRING  	1802
#define IDCB_GPPS_SZSECTION             	1803
#define IDCB_GPPS_SZKEY                 	1804
#define IDCB_GPPS_SZDEFAULT             	1820
#define IDCK_GPPS_SZRETURNBUFFER        	1821
#define IDE_GPPS_CCHRETURNBUFFER        	1822
#define IDD_SQLINSTALLDRIVER            	1823
#define IDCB_ID_SZINFFILE               	1824
#define IDCB_ID_SZDRIVER                	1825
#define IDCK_ID_SZPATH                  	1826
#define IDE_ID_CBPATHMAX                	1827
#define IDCK_ID_PCBPATHOUT              	1828
#define IDD_SQLINSTALLDRIVERMANAGER     	1840
#define IDE_IDM_CBPATHMAX               	1841
#define IDCK_IDM_PCBPATHOUT             	1860
#define IDCK_IDM_SZPATH                 	1880
#define IDD_SQLINSTALLODBC              	1881
#define IDCB_IODBC_SZINF                	1900
#define IDCB_IODBC_SZSRC                	1901
#define IDCB_IODBC_SZDRIVERS            	1902
#define IDCK_IODBC_HWNDPARENT           	1903
#define IDD_SQLINSTALLTRANSLATOR       	1920
#define IDCB_IT_SZINFFILE               	1921
#define IDCB_IT_SZTRANSLATOR            	1940
#define IDCB_IT_SZPATHIN                	1941
#define IDCK_IT_SZPATHOUT               	1942
#define IDE_IT_CBPATHOUTMAX             	1960
#define IDCK_IT_PCBPATHOUT              	1961
#define IDCB_IT_FREQUEST                	1980
#define IDCK_IT_DWUSAGECOUNT            	1981
#define IDD_SQLMANAGEDATASOURCES        	1982
#define IDCK_MDS_HWND                   	1983
#define IDD_SQLREMOVEDEFAULTDATASOURCE  	1984
#define IDD_SQLREMOVEDSNFROMINI         	1985
#define IDCB_RDSNFI_SZDSN               	1986
#define IDD_SQLREMOVEDRIVER             	1987
#define IDCB_RD_SZDRIVER                	1988
#define IDCB_RD_FREQUEST                	1989
#define IDCK_RD_DWUSAGECOUNT            	1990
#define IDD_SQLREMOVEDRIVERMANAGER      	1991
#define IDCK_RDM_DWUSAGECOUNT           	2000
#define IDD_SQLREMOVETRANSLATOR         	2001
#define IDCB_RT_SZTRANSLATOR            	2002
#define IDCK_RT_DWUSAGECOUNT            	2003
#define IDD_SQLVALIDDSN                 	2020
#define IDCB_VDSN_SZDSN							2021
#define IDD_SQLWRITEDSNTOINI            	2022
#define IDCB_WDSNTI_SZDSN               	2023
#define IDCB_WDSNTI_SZDRIVER            	2024
#define IDD_SQLWRITEPRIVATEPROFILESTRING	2025
#define IDCB_WPPS_SZSECTION             	2026
#define IDCB_WPPS_SZKEY                 	2027
#define IDCB_WPPS_SZSTRING              	2028
#define IDD_SQLGETTRANSLATOR            	2039
#define IDCK_GT_HWNDPARENT              	2040
#define IDCB_GT_SZNAME                  	2041
#define IDE_GT_CBNAMEMAX                	2042
#define IDCK_GT_PCBNAMEOUT              	2043
#define IDCK_GT_SZPATH                  	2044
#define IDE_GT_CBPATHMAX                	2045
#define IDCK_GT_PCBPATHOUT              	2046
#define IDCK_GT_PVOUT                   	2047
#define IDD_FILLPARAM                   	2048
#define IDC_FP_HSTMT_LABEL              	2049
#define IDC_FP_HSTMT                    	2050
#define IDC_FP_IPAR                     	2051
#define IDC_FP_ROW                      	2052
#define IDC_FP_FPARAMTYPE_LABEL         	2053
#define IDC_FP_FPARAMTYPE               	2054
#define IDC_FP_FCTYPE_LABEL             	2056
#define IDC_FP_FCTYPE                   	2058
#define IDC_FP_FSQLTYPE_LABEL           	2059
#define IDC_FP_FSQLTYPE                 	2060
#define IDC_FP_CBCOLDEF_LABEL           	2061
#define IDC_FP_CBCOLDEF                 	2062
#define IDC_FP_IBSCALE_LABEL            	2063
#define IDC_FP_IBSCALE                  	2064
#define IDC_FP_RGBVALUE                 	2065
#define IDC_FP_CBVALUEMAX_LABEL         	2066
#define IDC_FP_CBVALUEMAX               	2080
#define IDC_FP_PCBVALUE                 	2081
#define IDC_FP_MACRO                    	2082
#define IDC_FP_RS_HDBC_LABEL            	2083
#define IDC_FP_RS_HDBC                  	2084
#define IDC_FP_RS_HSTMT_LABEL           	2085
#define IDC_FP_RS_HSTMT                 	2086
#define IDC_FP_RS_COLUMN_LABEL          	2087
#define IDC_FP_RS_COLUMN                	2088
#define IDC_FP_RS_ROW_LABEL             	2089
#define IDC_FP_RS_ROW                   	2090
#define IDD_UPDATECELL                  	2091
#define IDC_UC_HSTMT                    	2092
#define IDC_UC_BOUND_COL                	2340
#define IDC_UC_BOUND_ROW                	2341
#define IDC_UC_STAT_RGBVALUE            	2342
#define IDC_UC_RGBVALUE                 	2343
#define IDC_UC_STAT_PCBVALUE            	2344
#define IDC_UC_PCBVALUE                 	2345
#define IDC_UC_SQL_LEN_MACRO            	2346
#define IDC_UC_FCTYPE                   	2347
#define IDC_UC_FCTYPE_VAL               	2348
#define IDC_UC_CBVALUEMAX               	2349
#define IDC_UC_CBVALUEMAX_VAL           	2360
#define IDD_SQLTABLES25                 	2361
#define IDCB_T25_QUALIFIER              	2362
#define IDCB_T25_OWNER                  	2363
#define IDCB_T25_NAME                   	2364
#define IDCB_T25_TYPE                   	2365
#define IDCB_T25_CBQUALIFIER            	2366
#define IDCB_T25_CBOWNER                	2367
#define IDCB_T25_CBNAME                 	2368
#define IDCB_T25_CBTYPE                 	2369
#define IDCK_T25_HSTMT                  	2380
#define IDD_SQLCOLUMNS25                	2381
#define IDCB_C25_TABLEQUALIFIER         	2382
#define IDCB_C25_TABLEOWNER             	2383
#define IDCB_C25_TABLENAME              	2384
#define IDCB_C25_COLNAME                	2385
#define IDCB_C25_CBQUALIFIER            	2386
#define IDCB_C25_CBOWNER                	2387
#define IDCB_C25_CBNAME                 	2388
#define IDCB_C25_CBCOLNAME              	2389
#define IDCK_C25_HSTMT                  	2400
#define IDD_SQLSTATISTICS25             	2401
#define IDCB_S25_TABLEQUALIFIER         	2402
#define IDCB_S25_TABLEOWNER             	2403
#define IDCB_S25_TABLENAME              	2404
#define IDCB_S25_FUNIQUE                	2405
#define IDCB_S25_QUALIFIER              	2406
#define IDCB_S25_OWNER                  	2407
#define IDCB_S25_NAME                   	2408
#define IDCB_S25_FACCURACY              	2409
#define IDCK_S25_HSTMT                  	2420
#define IDD_SQLPRIMARYKEYS25            	2421
#define IDCB_PK25_SZTABLELABEL          	2422
#define IDCB_PK25_QUALIFIER             	2423
#define IDCB_PK25_OWNER                 	2424
#define IDCB_PK25_NAME                  	2425
#define IDCB_PK25_CBTABLE               	2426
#define IDCB_PK25_CBQUALIFIER           	2427
#define IDCB_PK25_CBOWNER               	2428
#define IDCB_PK25_CBNAME                	2429
#define IDCK_PK25_HSTMT                 	2430
#define IDD_SQLFOREIGNKEYS25            	2431
#define IDCB_FK25_QUALIFIER             	2432
#define IDCB_FK25_OWNER                 	2433
#define IDCB_FK25_NAME                  	2440
#define IDCB_FK25_CBQUALIFIER           	2441
#define IDCB_FK25_CBOWNER               	2442
#define IDCB_FK25_CBNAME                	2443
#define IDCB_FK25_FKQUALIFIER           	2444
#define IDCB_FK25_FKOWNER               	2445
#define IDCB_FK25_FKNAME                	2446
#define IDCB_FK25_CBFKQUALIFIER         	2447
#define IDCB_FK25_CBFKOWNER             	2460
#define IDCB_FK25_CBFKNAME              	2461
#define IDCK_FK25_HSTMT                 	2462
#define IDD_SQLTABLEPRIVILEGES25        	2463
#define IDCB_TP25_QUALIFIER             	2464
#define IDCB_TP25_OWNER                 	2465
#define IDCB_TP25_NAME                  	2466
#define IDCB_TP25_CBQUALIFIER           	2467
#define IDCB_TP25_CBOWNER               	2468
#define IDCB_TP25_CBNAME                	2469
#define IDCK_TP25_HSTMT                 	2480
#define IDD_SQLCOLUMNPRIVILEGES25       	2481
#define IDCB_CP25_QUALIFIER             	2482
#define IDCB_CP25_OWNER                 	2483
#define IDCB_CP25_NAME                  	2484
#define IDCB_CP25_COLNAME               	2485
#define IDCB_CP25_TABLEQUALIFIER        	2486
#define IDCB_CP25_TABLEOWNER            	2487
#define IDCB_CP25_TABLENAME             	2488
#define IDCB_CP25_CBCOLNAME             	2489
#define IDCK_CP25_HSTMT                 	2490
#define IDD_SQLSPECIALCOLUMNS25         	2500
#define IDCB_SC25_FCOLTYPE              	2501
#define IDCB_SC25_QUALIFIER             	2502
#define IDCB_SC25_OWNER                 	2503
#define IDCB_SC25_NAME                  	2504
#define IDCB_SC25_CBQUALIFIER           	2505
#define IDCB_SC25_CBOWNER               	2506
#define IDCB_SC25_CBNAME                	2507
#define IDCB_SC25_FSCOPE                	2520
#define IDCB_SC25_FNULLABLE             	2521
#define IDCK_SC25_HSTMT                 	2522
#define IDD_SQLPROCEDURES25             	2523
#define IDCB_P25_QUALIFIER              	2524
#define IDCB_P25_OWNER                  	2525
#define IDCB_P25_NAME                   	2526
#define IDCB_P25_CBQUALIFIER            	2527
#define IDCB_P25_CBOWNER                	2528
#define IDCB_P25_CBNAME                 	2529
#define IDCK_P25_HSTMT                  	2601
#define IDD_SQLPROCEDURECOLUMNS25       	2602
#define IDCB_PC25_QUALIFIER             	2603
#define IDCB_PC25_OWNER                 	2604
#define IDCB_PC25_NAME                  	2605
#define IDCB_PC25_COLNAME               	2606
#define IDCB_PC25_CBPROCQUALIFIER       	2700
#define IDCB_PC25_CBPROCOWNER           	2701
#define IDCB_PC25_CBPROCNAME            	2702
#define IDCB_PC25_CBCOLNAME             	2703
#define IDCK_PC25_HSTMT                 	2704
#define IDE_IE_IERROR                   	2705
#define IDCK_IE_PFERRORCODE             	2706
#define IDCK_IE_SZERRORMSG              	2707
#define IDE_IE_CBERRORMSGMAX            	2708
#define IDCK_IE_PCBERRORMSG             	2709
#define IDD_SQLINSTALLERERROR           	2710
#define IDD_SQLGETSUBSTRING             	2711
#define IDCK_GSS_HSTMT                  	2712
#define IDCB_GSS_FLOCATORTYPE           	2713
#define IDCB_GSS_HSOURCELOCATOR         	2714
#define IDE_GSS_IFROMPOSITION           	2715
#define IDE_GSS_CBFORLENGTH             	2716
#define IDCB_GSS_FTARGETTYPE            	2717
#define IDCB_GSS_RGBVALUE               	2718
#define IDE_GSS_CBVALUEMAX              	2719
#define IDCK_GSS_PCBVALUE               	2720
#define IDCK_GSS_PFINDICATOR            	2800
#define IDD_SQLGETAVAILABLEDRIVERS      	2801
#define IDCB_GAD_SZINFFILE              	2802
#define IDCK_GAD_SZBUF                  	2803
#define IDE_GAD_CBBUFMAX                	2804
#define IDCK_GAD_PCBBUFOUT              	2805
#define IDC_DISPLAY_HANDLE              	2806
#define IDC_DISPLAY_HANDLE2             	2807
#define IDR_FC_DEFAULT                  	2808
#define IDR_FC_ODBC2X                   	2809
#define IDR_FC_ODBC30                   	2810
#define IDC_PDH_HDESC                   	2811
#define IDD_PICK_HDESC                  	2812
#define IDCB_IDEX_SZINFFILE             	2813
#define IDCB_IDEX_SZDRIVER              	2814
#define IDCK_IDEX_SZPATHIN              	2815
#define IDE_IDEX_CBPATHOUTMAX           	2816
#define IDCK_IDEX_PCBPATHOUT            	2817
#define IDCK_IDEX_SZPATHOUT             	2818
#define IDCB_PIE_FERRORCODE             	2819
#define IDCB_IDEX_FREQUEST              	2820
#define IDCB_PIE_SZERRORMSG             	2821
#define IDCK_IDEX_LPDWUSAGECOUNT        	2822
#define IDCK_RFD_HWNDPARENT             	2823
#define IDCB_RFD_LPSZFILENAME           	2824
#define IDCK_RFD_LPSZSTRING             	2825
#define IDCK_RFD_PCBSTRING              	2826
#define IDCB_RFD_LPSZAPPNAME            	2827
#define IDCB_RFD_LPSZKEYNAME            	2828
#define IDCB_WFD_LPSZSTRING             	2829
#define IDCB_WFD_LPSZFILENAME           	2830
#define IDCB_WFD_LPSZAPPNAME            	2831
#define IDCB_WFD_LPSZKEYNAME            	2832
#define IDCK_WFD_HWNDPARENT             	2833
#define IDE_RFD_CBSTRING                	2834
#define IDD_SQLINSTALLDRIVEREX          	2835
#define IDD_SQLPOSTINSTALLERERROR       	2836
#define IDD_SQLREADFILEDSN              	2837
#define IDD_SQLWRITEFILEDSN             	2838
#define IDR_FC_ODBC40                   	2839
#define IDD_INTERVAL_STRUCT					2900
#define IDE_INTERVAL_YEAR						2901
#define IDE_INTERVAL_MONTH						2902
#define IDE_INTERVAL_DAY						2903
#define IDE_INTERVAL_HOUR						2904
#define IDE_INTERVAL_MINUTE					2905
#define IDE_INTERVAL_SECOND					2906
#define IDE_INTERVAL_FRACTION					2907
#define IDE_INTERVAL_MONTH_TXT				2908
#define IDE_INTERVAL_YEAR_TXT					2909
#define IDE_INTERVAL_DAY_TXT					2910
#define IDE_INTERVAL_HOUR_TXT					2911
#define IDGB_YEAR_MONTH_STRUCT				2912
#define IDGB_DAY_SECOND_STRUCT				2913
#define IDCB_INTERVAL_TYPE						2914
#define IDCB_INTERVAL_SIGN						2915
#define IDC_INTERVAL_SIGN_TXT					2916
#define IDE_INTERVAL_SECOND_TXT				2917
#define IDE_INTERVAL_FRACTION_TXT			2918
#define IDE_INTERVAL_MINUTE_TXT				2930
#define IDC_INTERVAL_TYPE_TXT					2931
#define IDD_LOAD_DESCRIPTOR_DEFAULTS		2932
#define IDC_LDD_HDESC							2933
#define IDG_ODBC_BEHAVIOR_GROUP				2934
#define IDG_CURSOR_LIBRARY_GROUP				2935
#define IDD_SQLBULKOPERATIONS					3000
#define IDCB_BO_OPERATION						3001
#define IDCB_BO_HSTMT							3002
#define IDD_SQLGETCONFIGMODE					3010
#define IDCK_GCM_PWCONFIGMODE					3011
#define IDD_SQLSETCONFIGMODE					3020
#define IDCB_SCM_WCONFIGMODE					3021
#define IDD_MANAGE_TYPES						3100
#define IDT_TYPE									3101
#define IDC_TYPES									3102
#define IDB_NEW									3103
#define IDB_DELETE								3104
#define IDT_TYPES_INSTALLED					3105
#define IDT_TYPES_AVAIL							3106
#define IDL_INSTALLED							3107
#define IDT_TYPE_AVAIL							3108
#define IDB_ADD									3109
#define IDB_REMOVE								3110
#define IDL_AVAILABLE							3111
#define IDCB_TYPES_LIST_TXT					3112
#define IDCB_TYPES_LIST							3113
#define IDD_NEW_GROUP							3114
#define IDE_GROUP									3115

#define IDD_CURSOR_ATTR                 3150
#define IDCB_CA_BIND_TYPE               3151
#define IDCB_CA_CURSOR_TYPE             3152
#define IDT_CA_CURSOR_TYPE              3153
#define IDT_CA_BIND_TYPE                3154
#define IDT_CA_CONCURRENCY              3155
#define IDCB_CA_CONCURRENCY             3156
#define IDT_CA_USE_BOOKMARKS            3157
#define IDCB_CA_USE_BOOKMARKS           3158
#define IDT_CA_ROW_ARRAY_SIZE           3159
#define IDE_CA_ROW_ARRAY_SIZE           3160
#define IDT_CA_ROWSET_SIZE              3161
#define IDE_CA_ROWSET_SIZE              3162
#define IDT_CA_HANDLE                   3163
#define IDCB_CA_HANDLE                  3164

#define IDCB_ST_SZCATALOGNAME            	3170
#define IDCB_ST_SZSCHEMANAME             	3171
#define IDCB_ST_SZTYPENAME              	3172
#define IDCB_ST_CBCATALOGNAME            	3173
#define IDCB_ST_CBSCHEMANAME             	3174
#define IDCB_ST_CBTYPENAME              	3175
#define IDCK_ST_HSTMT                    	3176

#define IDCB_STC_SZCATALOGNAME          	3180
#define IDCB_STC_SZSCHEMANAME           	3181
#define IDCB_STC_SZTYPENAME              	3182
#define IDCB_STC_SZCOLUMNNAME           	3183
#define IDCB_STC_CBCATALOGNAME          	3184
#define IDCB_STC_CBSCHEMANAME           	3185
#define IDCB_STC_CBTYPENAME              	3186
#define IDCB_STC_CBCOLUMNNAME           	3187
#define IDCK_STC_HSTMT                  	3188

//Options Tabbed Dialog
#define IDTD_USER_AUT_OPTIONS					3200
#define IDTD_USER_MENU_VER						3201
#define IDTD_USER_BUFFER_LEN					3202
#define IDTD_USER_MISC							3203
#define IDTD_USER_ROWSET_OPTIONS				3204
#define IDC_ROWSET_OPT_DISPLAY_AUTO			3205
#define IDTD_TABS_BASE							IDTD_USER_AUT_OPTIONS


#define IDD_SQLINSTALLTRANSLATOREX	      	3220
#define IDCB_ITEX_SZINFFILE               	3221
#define IDCB_ITEX_SZTRANSLATOR            	3222
#define IDCB_ITEX_SZPATHIN                	3223
#define IDCK_ITEX_SZPATHOUT               	3224
#define IDE_ITEX_CBPATHOUTMAX             	3225
#define IDCK_ITEX_PCBPATHOUT              	3226
#define IDCB_ITEX_FREQUEST                	3227
#define IDCK_ITEX_DWUSAGECOUNT            	3228
